"""auto-vote

Revision ID: 5ad86e739393
Revises: d84543f65c7c
Create Date: 2024-07-30 05:11:16.374510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad86e739393'
down_revision: Union[str, None] = 'd84543f65c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('us_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['us_id'], ['users.u_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('us_id', 'po_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
