"""add u phone number

Revision ID: b996c93f0066
Revises: 5ad86e739393
Create Date: 2024-07-30 05:14:34.239400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b996c93f0066'
down_revision: Union[str, None] = '5ad86e739393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('u_phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'u_phone_number')
    # ### end Alembic commands ###
